/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;

/**
 *
 * @author JAIRO
 */
public class GUIBusquedad extends javax.swing.JFrame {

    /**
     * Creates new form GUIBusquedad
     */
   public GUIBusquedad(ActionListener control, ItemListener controlador) {
        initComponents();
       panelTabla1.escucharBoton(control);
        panelTabla1.escucharCombo(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTabla1 = new vista.PanelTabla();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTabla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTabla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.PanelTabla panelTabla1;
    // End of variables declaration//GEN-END:variables

    public void editableCampoBuscar(boolean estado){
    panelTabla1.editableCampoBuscar(estado);
    }
    
     public void setValores(String [][] datosFilas,String etiquetas[]){
         panelTabla1.setValores(datosFilas, etiquetas);
     }
     
      public String getConsulta() {
      return panelTabla1.getConsulta();
     
      }
     public String getCombo() {
     return panelTabla1.getCombo();
     }
     
      public void setEtiqueta(String etiqueta){
          panelTabla1.setEtiqueta(etiqueta);
      }
      public void limpiar()
      {panelTabla1.limpiar();}
 
      public void desbloquearMatricula(boolean block)
    {
    panelTabla1.desbloquearMatricula(block);
    }
        
      
}
