/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
// uva ves registrado donde ves los cursos??no he echo bueno eso es una tabla dinamica 
// los cursos cuando los matriclas ya los guardas en un array lis o como lo haces ?? diay si valla a registro curso

import controlador.ControlEstudiante;
import java.awt.event.ActionListener;

/**
 *
 * @author JAIRO
 */
public class PanelCurso extends javax.swing.JPanel {

    /**
     * Creates new form PanelCurso
     */
    public PanelCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFinalizar = new javax.swing.JButton();
        jc_programacion = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jc_Manipulacion = new javax.swing.JCheckBox();
        jc_Historia = new javax.swing.JCheckBox();
        jc_Bases = new javax.swing.JCheckBox();
        btnCancelar = new javax.swing.JButton();

        btnFinalizar.setText("Finalizar Registro");

        jc_programacion.setText("Programación");
        jc_programacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_programacionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Lista Cursos");

        jc_Manipulacion.setText("Manipulación de la imagen");

        jc_Historia.setText("Historia de las artes visuales");

        jc_Bases.setText("Base de Datos");
        jc_Bases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_BasesActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(btnFinalizar)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jc_Historia)
                            .addComponent(jc_programacion)
                            .addComponent(jc_Manipulacion)
                            .addComponent(jc_Bases)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jc_programacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jc_Manipulacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jc_Historia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jc_Bases)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizar)
                    .addComponent(btnCancelar))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jc_programacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_programacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc_programacionActionPerformed

    private void jc_BasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_BasesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc_BasesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox jc_Bases;
    private javax.swing.JCheckBox jc_Historia;
    private javax.swing.JCheckBox jc_Manipulacion;
    private javax.swing.JCheckBox jc_programacion;
    // End of variables declaration//GEN-END:variables
 public static final String BTN_CANCELAR = "cancelar";
  public static final String BTN_FINALIZAR = "Finalizar Registro";
public static final String JC_PROGRAMACION="Programación";
public static final String JC_HISTORIA="Historia de las artes visuales";
public static final String JC_MANIPULACION="Manipulación de la imagen";
public static final String JC_BASES="Base de Datos";

    public void escucharBtn(ActionListener control,ActionListener ac) {
        
        this.btnCancelar.addActionListener(control);
        this.btnFinalizar.addActionListener(control);
        this.jc_programacion.addActionListener(ac);
        this.jc_Bases.addActionListener(ac);
        this.jc_Historia.addActionListener(ac);
        this.jc_Manipulacion.addActionListener(ac);
}


    
}
