/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author usuario
 */
public class PanelTabla extends javax.swing.JPanel {

    /**
     * Creates new form PanelTabla
     */
    public PanelTabla() {
        initComponents();
        btn_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"--seleccionar--", "All", "Nombre", "Carnet"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbBuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_combo = new javax.swing.JComboBox();
        txtbuscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_atras = new javax.swing.JButton();
        btnMatricula = new javax.swing.JButton();

        jLabel1.setText("Filtro:");

        lbBuscar.setText("Carnet:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Carnet ", "Nombre", "Edad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        btn_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comboActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Busquedad Estudiantes");

        btn_atras.setText("Atras");

        btnMatricula.setText("Matricular");
        btnMatricula.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lbBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMatricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_atras)
                                .addGap(42, 42, 42))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(93, 93, 93)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBuscar)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_atras)
                    .addComponent(btnMatricula))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_comboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMatricula;
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JComboBox btn_combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables

    public static final String BTN_BUSCAR="Buscar";
    public static final String BTN_AGREGAR="/img/tit_icono (1).png";
   public static final String BTN_ATRAS="Atras";
   public static final String BTN_MATRICULA="Matricular";
    public void escucharBoton(ActionListener control){
        this.btn_buscar.addActionListener(control);
        this.btn_atras.addActionListener(control);

        this.btnMatricula.addActionListener(control);
    }
     public void escucharCombo(ItemListener controlador){
        this.btn_combo.addItemListener(controlador);
    }
     public void setValores(String [][] datosFilas,String etiquetas[]){
 if(datosFilas !=null){
 jTable1.setModel(new javax.swing.table.DefaultTableModel(datosFilas,etiquetas));
 
 }} 
  public String[] getdatosFila() {
        String datos[] = new String[jTable1.getColumnCount()];
        int filaSeleccionada = jTable1.getSelectedRow();
        for (int columna = 0; columna < datos.length; columna++) {
            datos[columna] = jTable1.getValueAt(filaSeleccionada, columna).toString().trim();
        }
        return datos;
    }
  public void limpiar(){
        txtbuscar.setText("");
    }
  
 
  
 public String getConsulta() {
        return this.txtbuscar.getText();
    }

    public String getCombo() {
        return this.btn_combo.getSelectedItem().toString();
    }
    
    public void setEtiqueta(String etiqueta){
        this.lbBuscar.setText(etiqueta);
    }
    
    public String getCampoBuscar(){
        return this.txtbuscar.getText();
    }
    public void editableCampoBuscar(boolean estado){
        this.txtbuscar.setEnabled(estado);
    }
    
    public void desbloquearMatricula(boolean block)
    {
    btnMatricula.setEnabled(block);
    }
      public String getCarnet()
    {return txtbuscar.getText().trim();}
}  
    

